### ISSUE TITLE
Hacker News blocking?

### ISSUE THREAD

**Issue by rattrayalex** [tobiasdalhof/sanersocialmedia#23]
Does this support blocking news.ycombinator.com's news feed?

Ideally would block:
1. The main page
2. /newest
3. /front

News Feed Eradicator supports blocking the main page of HN.

**Comment by tobiasdalhof** [comment]
Adding support for HN when I find some time

**Comment by tobiasdalhof** [comment]
Pull requests are open if you want to contribute

**Comment by tobiasdalhof** [comment]
Published [v1.6.0](https://github.com/tobiasdalhof/sanersocialmedia/releases/tag/v1.6.0)

Review pending

**Comment by rattrayalex** [comment]
Amazing thank you!
