### ISSUE TITLE
Productivity and Flow...

### ISSUE THREAD

**Issue by Revanth736** [tobiasdalhof/sanersocialmedia#29]
Hey , thank you for your extension , it's really usefull for me to do my work in social media whilst avoiding their cunning distractions really good Job!! ,however there is minor problem , the qoutes are ditracting me while I am working and is killing my flow , How do you think you can solve this issue?

**Comment by tobiasdalhof** [comment]
Hi @Revanth736,
We can add an option to display custom text instead of quotes. The custom text can be HTML or left blank to show nothing. Would that solve your issue?
