### ISSUE TITLE
Facebook broken?

### ISSUE THREAD

**Issue by tobiasdalhof** [tobiasdalhof/sanersocialmedia#41]
![image](https://github.com/tobiasdalhof/sanersocialmedia/assets/10046578/87ecddaa-f395-4b4e-8be7-5e4185c588bf)

Need to check, don't have a Facebook account right now / I don't use Facebook

**Comment by sorae42** [comment]
Facebook change its css class almost every week so that's the reason why.

**Comment by tobiasdalhof** [comment]
Can't reproduce

![image](https://github.com/user-attachments/assets/1c2cb113-23fc-44a4-874d-fca3e36cd2df)
