### ISSUE TITLE
Facebook changed its url

### ISSUE THREAD

**Issue by sorae42** [tobiasdalhof/sanersocialmedia#43]
Facebook now redirect to web.facebook.com instead of www.facebook.com.

**Comment by tobiasdalhof** [comment]
`web.facebook.com` should be covered by our manifest @ https://github.com/tobiasdalhof/sanersocialmedia/blob/main/extension/manifest.json#L22

It's probably not working because the CSS selectors have changed

**Comment by sorae42** [comment]
That makes sense, Facebook did something do its layout. The reels and post redirection is broken atm.

**Comment by sorae42** [comment]
Turns out I used mobile data thru my phone tether connection and Facebook keep redirecting me to web.facebook.com.

Once I'm back to my wifi, Facebook works as normal on www.facebook.com (no redirect) and feed blocking happens to work flawlessly.

Facebook is really weird how they works.
