### ISSUE TITLE
feature request: youtube mobile website

### ISSUE THREAD

**Issue by aryairani** [tobiasdalhof/sanersocialmedia#45]
I'm using Saner Social Media on my phone and noticed it works great for Reddit but less great for YouTube. However, it does seem to work normally for YouTube if I "Request Desktop Site", but that's not the default.

Thanks for all your work!

![image](https://github.com/user-attachments/assets/7cb18c84-9332-4e43-b3fc-ed6b3e135ecc)

![image](https://github.com/user-attachments/assets/54394994-4ba5-4ded-95f9-6b3d9944eb83)

![image](https://github.com/user-attachments/assets/a7224bf7-3c00-463e-9ad1-1757b09833e3)

**Comment by tobiasdalhof** [comment]
I'll prepare a PR:

https://github.com/user-attachments/assets/31bcebfa-0684-4f96-b1dd-be34c321364f

**Comment by tobiasdalhof** [comment]
Submitted new version, review pending

**Comment by aryairani** [comment]
Wow that was incredible! Thanks!

**Comment by aryairani** [comment]
Worked for me: ![image](https://github.com/user-attachments/assets/fd10baab-a7b1-458b-b442-f034f77b64fb)

**Comment by aryairani** [comment]
Actually I just noticed that the Subscriptions pane isn't blocked, although I don't have an opinion currently about whether it should be or not.

**Comment by tobiasdalhof** [comment]
> Actually I just noticed that the Subscriptions pane isn't blocked, although I don't have an opinion currently about whether it should be or not.

I often find myself wasting time on the subscriptions feed 😅. Unfortunately, there's no option to block it right now because the last time I tried to implement this, I ran into some tricky edge cases that made it challenging.

**Comment by aryairani** [comment]
No problem!
