### ISSUE TITLE
Development on macOS: `copy-extension-dir` fails

### ISSUE THREAD

**Issue by scorchio** [tobiasdalhof/sanersocialmedia#49]
Hi,

When I started to play around with a fork, I noticed that on my macOS system the `pnpm dev` fails with this:
```
> cp -T -r ./extension ./dist

cp: illegal option -- T
```

As a workaround, I could get past this by removing the `-T` in the command in the package.json.

**Comment by tobiasdalhof** [comment]
Thanks for catching this macOS compatibility issue! I'll remove the `-T` flag in the next commit since it works fine without it.
